@file:Suppress("PackageDirectoryMismatch")

/*
 * Schema generated by DataFrame.generateInterfaces method.
 *
 * BUG: Kotlin Dataframe failed to resolve schemas when are placed in a package different from the code target that used
 * it.
 *
 * In order to preserve a clean organization implementing interfaces and data classes in separated files and physical
 * package locations (at folder and file level) we suppress the issue in these files.
 */
package org.example.ine.services

import org.jetbrains.kotlinx.dataframe.annotations.DataSchema

/** @suppress  */
@Suppress("PropertyName", "unused")
@DataSchema
interface IneCityExcelRowSchema {
    val CMUN: String
    val CODAUTO: String
    val CPRO: String
    val DC: String
    val NOMBRE: String
}